#!/bin/bash
usage() {
  cat <<EOF
USAGE:
  kubenpod <NODE_NAME>          : list all pods of the <NODE_NAME>
  kubenpod -p <POD_NAME>        : list all pods of the <POD_NAME>'s node 
  kubenpod                      : show this message
  kubenpod -h,--help            : show this message
EOF
}
top_pod() {	
	IFS=$'\r\n' GLOBIGNORE='*' command eval  'XYZ=($(kubectl get pod  -A --field-selector spec.nodeName="${1}" --no-headers))'
	pod_output=$(kubectl top pod -A --no-headers)
	for (( i=0; i<${#XYZ[@]}; i++ ));
	do
	        echo -e "${pod_output}" | grep $(echo "${XYZ[$i]}" | awk '{print $2}')
	done
}
if [[ "${1}" == '-p' ]]; then
	pod_ns=$(kubectl get pods -A | grep ${2} | awk '{print $1}')
	pod_no=$(kubectl get pods -n ${pod_ns} ${2} --no-headers -o=custom-columns=pod_no:.spec.nodeName)
	echo kubenpod ${pod_no}
	top_pod "${pod_no}"
elif [[ "${1}" == '-h' || "${1}" == '--help' || -z "${1}" ]]; then
      usage
else
	top_pod "${1}"
fi
