#!/bin/bash
IFS=$'\r\n' GLOBIGNORE='*' command eval  'XYZ=($(kubectl get pod  -A --field-selector spec.nodeName="${1?	Error: node ip girilmedi.	Örnek kullanım: kubentop ip-10-0-0-1.eu-central-1.compute.internal}" --no-headers))'
pod_output=$(kubectl top pod -A --no-headers)
for (( i=0; i<${#XYZ[@]}; i++ ));
do
        echo -e "${pod_output}" | grep $(echo "${XYZ[$i]}" | awk '{print $2}')
done
